### ISSUE TITLE
Single SMTP connection

### ISSUE THREAD

**Issue by AndreaCrotti** [syrusakbary/validate_email#13]
Using the library to check a lot of email addresses in batch I'm noticing that the SMTP server disconnects me after a certain number of connections.

I was thinking I could just use a single SMTP connection instead and close it at the end, for example caching the connections as well, and forcing an explicit quit somehow.
What do you think?

**Comment by jeechu** [comment]
@AndreaCrotti Could you make it work? I need to verify a large set of email in batches, and was wondering what other issues could come up in doing that.. Did you find anything else?
