### ISSUE TITLE
Doesn't returns anything

### ISSUE THREAD

**Issue by Steve667** [syrusakbary/validate_email#33]
Hello there :)
I´m having a little issue with your library: it doesn't returns anything, a NonType Object. What I'm trying to do is to verify an account that does exists but I'm new in all of this. I have pyDNS and validate_email imported (import DNS; from validate_email import validate_email) When I try to verify the email, it returns a NoneType, nor a true or a false. Am I missing something? Thanks for your attention :)

**Comment by anurag-banerjee** [comment]
If the validate_email() function returns a NoneType, then the email address you looked up does not exist or does not appear to exist. When the email address does exist, it would return True.

**Comment by Steve667** [comment]
Thanks for the reply, I think that it was being blocked by a firewall and wasn't comunicating to the outside (was trying to validate my own email, but thanks for the reply, I'll be waiting a NoneType as a reply of a non-existent account :+1: ). But I have another little problem (I don't know if I should close this issue and open another). I'm trying to validate the account hahahaha@hahaha.ha and it returns True. I'm thinking that it could be an alias, but I'm not sure. Am I missing something? Thanks for your attention and replies :)
